version: "3.7"
services:
  web:
    image: jevprentice/docker-java12-pingpongservice:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8082"
    volumes:
      - /tmp/docker-java12-pingpongservice/data:/data
    networks:
      - docker-java12-pingpongservice-network
networks:
  docker-java12-pingpongservice-network:
    name: docker-java12-pingpongservice-network
