server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yet-another-spring-boot-docker-app
    username: postgres_username
    password: postgres_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: yet_another_schema
        hbm2ddl:
          auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false
  logging:
    level:
      root: WARN
      com.jevprentice: DEBUG
      org.springframework.web: INFO
      org.springframework.security: INFO
  mvc:

