server:
  port: 8088

spring:
  logging:
    level:
      root: WARN
      com.jevprentice: DEBUG
      org.springframework.web: INFO
      org.springframework.security: INFO
  datasource:
    platform: postgres
    url: jdbc:postgresql://host.docker.internal:5432/yet_another_spring_boot_docker_app
    username: postgres_username
    password: postgres_password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        hbm2ddl:
          auto: create-drop
  mvc:

